[dataset]
class = "QuickDrawDataset"
label_names = ["bird", "crab", "guitar"]
download = true

[tokenizer]
class = "DeltaPenPositionTokenizer"
bins = 32

[model]
class = "SketchTransformerConditional"
d_model = 512
nhead = 8
num_layers = 8
max_len = 200
num_classes = 3

[training]
batch_size = 128
num_epochs = 20
learning_rate = 1e-4
log_dir = "logs/sketch_transformer_example3"
resume = false
use_padding_mask = true
splits = [0.85, 0.1, 0.05]
