[dataset]
class = "QuickDrawDataset"
label_names = ["cat", "dog", "bird", "fish", "crab", "guitar", "sailboat", "bulldozer", "apple", "monkey", "skull", "whale"]
download = true

[tokenizer]
class = "DeltaPenPositionTokenizer"
bins = 32

[model]
class = "SketchTransformerConditional"
d_model=768
nhead=12
num_layers=10
max_len = 200
num_classes = 12

[training]
batch_size = 128
num_epochs = 15
learning_rate = 1e-4
log_dir = "logs/sketch_transformer_experiment_5"
splits = [0.85, 0.075, 0.075]
checkpoint_path = "logs/sketch_transformer_experiment_5/20251114_193327/model_1.pt"