[dataset]
class = "QuickDrawDataset"
label_names = ["cat"]
download = true

[tokenizer]
class = "AbsolutePenPositionTokenizer"
bins = 32

[model]
class = "SketchTransformer"
d_model = 384
nhead = 16
num_layers = 6
max_len = 200

[training]
batch_size = 128
num_epochs = 15
learning_rate = 1e-4
log_dir = "logs/sketch_transformer_example0"
splits = [0.85, 0.1, 0.05]

# checkpoint_path is a path to the model_{epoch}.pt file
# note the model parameters must be the same to continue from a checkpoint

# checkpoint_path = "logs/sketch_transformer_example0/20251109_220241/model_4.pt"
