[dataset]
class = "QuickDrawDataset"
label_names = ["cat"]
download = true

[tokenizer]
class = "DeltaPenPositionTokenizer"
bins = 32

[model]
class = "SketchTransformer"
d_model = 384
nhead = 8
num_layers = 6
max_len = 200

[training]
batch_size = 128
num_epochs = 16
learning_rate = 1e-4
log_dir = "logs/sketch_transformer_example2"
use_padding_mask = true
splits = [0.85, 0.075, 0.075]